server:
  port: 8090
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 200
        max-idle: 20
        min-idle: 5
        max-wait: 1000


logging:
  level:
    root: info
    org.springframework: DEBUG
    org.springframework.web: DEBUG
