server:
  port: 8090

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 200
        max-idle: 20
        min-idle: 5
        max-wait: 1000
  output:
    ansi:
      enabled: always


# actuator 相关配置
info.app.author: chuan jiang
info.app.encoding: @project.build.sourceEncoding@

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

logging:
  level:
    root: info
    org.springframework.web: TRACE
    # org.springframework.boot.actuate: TRACE
